/** Claves de caché de React Query: una sola fuente para consultas e invalidaciones. */
export const queryKeys = {
  settings: ['settings'] as const,
  pinUsers: ['pin-users'] as const,
  setupStatus: ['setup-status'] as const,
  areas: ['areas'] as const,
  tables: ['tables'] as const,
  categories: ['categories'] as const,
  products: ['products'] as const,
  noteOptions: ['note-options'] as const,
  recipe: (productId: string) => ['recipe', productId] as const,
  orders: ['orders'] as const,
  order: (id: string) => ['orders', 'detail', id] as const,
  activeOrders: ['orders', 'active'] as const,
  tickets: ['kitchen-tickets'] as const,
  cash: ['cash'] as const,
  expenses: ['cash', 'expenses'] as const,
  invoices: ['invoices'] as const,
  ingredients: ['ingredients'] as const,
  movements: ['inventory-movements'] as const,
  inventoryAlerts: ['inventory-alerts'] as const,
  suppliers: ['suppliers'] as const,
  purchases: ['purchases'] as const,
  customers: ['customers'] as const,
  reports: ['reports'] as const,
  users: ['users'] as const,
  roles: ['roles'] as const,
  taxes: ['taxes'] as const,
  printers: ['printers'] as const,
  numberingRanges: ['numbering-ranges'] as const,
  system: ['system'] as const,
};
