name: Solicitud de funcionalidad
description: Propón una mejora o una capacidad nueva
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema del restaurante que resuelve
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Propuesta
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
