/**
 * Códigos de error estables de la API (`ApiErrorBody.code`). Los clientes deciden su
 * comportamiento por el código, nunca por el texto del mensaje.
 */
export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  IDEMPOTENCY_IN_PROGRESS: 'IDEMPOTENCY_IN_PROGRESS',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',

  ORDER_VERSION_CONFLICT: 'ORDER_VERSION_CONFLICT',
  ORDER_NOT_EDITABLE: 'ORDER_NOT_EDITABLE',
  ORDER_EMPTY: 'ORDER_EMPTY',
  /** Solo una cuenta sin productos ni pagos se cierra sin anularla (mesa abierta por error). */
  ORDER_NOT_EMPTY: 'ORDER_NOT_EMPTY',
  ORDER_HAS_PAYMENTS: 'ORDER_HAS_PAYMENTS',
  /** Hay productos de cocina o barra sin enviar: primero se envían, después se cobra. */
  ORDER_HAS_UNSENT_ITEMS: 'ORDER_HAS_UNSENT_ITEMS',
  ITEM_ALREADY_SENT: 'ITEM_ALREADY_SENT',
  PRODUCT_UNAVAILABLE: 'PRODUCT_UNAVAILABLE',
  TABLE_OCCUPIED: 'TABLE_OCCUPIED',
  TABLE_REQUIRED: 'TABLE_REQUIRED',
  /** Unir dejaría varias cuentas con consumo en la mesa principal: se pide confirmar. */
  TABLE_MERGE_NEEDS_CONFIRMATION: 'TABLE_MERGE_NEEDS_CONFIRMATION',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  DISCOUNT_LIMIT_EXCEEDED: 'DISCOUNT_LIMIT_EXCEEDED',

  CASH_SESSION_REQUIRED: 'CASH_SESSION_REQUIRED',
  CASH_SESSION_ALREADY_OPEN: 'CASH_SESSION_ALREADY_OPEN',
  PAYMENT_EXCEEDS_BALANCE: 'PAYMENT_EXCEEDS_BALANCE',
  INSUFFICIENT_TENDERED: 'INSUFFICIENT_TENDERED',

  NUMBERING_RANGE_EXHAUSTED: 'NUMBERING_RANGE_EXHAUSTED',
  FISCAL_PROVIDER_NOT_CONFIGURED: 'FISCAL_PROVIDER_NOT_CONFIGURED',
  PRINTER_UNREACHABLE: 'PRINTER_UNREACHABLE',
  PRINTER_NOT_SUPPORTED: 'PRINTER_NOT_SUPPORTED',

  SETUP_ALREADY_COMPLETED: 'SETUP_ALREADY_COMPLETED',
  LICENSE_INVALID: 'LICENSE_INVALID',
  BACKUP_UNAVAILABLE: 'BACKUP_UNAVAILABLE',
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
